# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35900c035fc78e270d1d4db9e89b5cbe1d42ae3d3bd681443472d39f362af8874a693762ae17609c3b568f957155e7e1d6855dd21c3ebc20b46db80b5a630be7

test:
  secret_key_base: ceda15cfc4a4f547845283033e760fa2708b749f938c3d2f23907f45f708cd6e30915501c66f5ed33373d257e9fd2f08b6684f049094e3661dc9e1b70f2aa487

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
